// Generated by script/import_maia_icons.py; edit the reviewed manifest instead.
import Foundation

enum DSIconName: String, CaseIterable {
    case check = "Maia-check"
    case checkCircle = "Maia-checkCircle"
    case accessibility = "Maia-accessibility"
    case chevronDown = "Maia-chevronDown"
    case chevronUp = "Maia-chevronUp"
    case chevronLeft = "Maia-chevronLeft"
    case chevronRight = "Maia-chevronRight"
    case chevronsVertical = "Maia-chevronsVertical"
    case arrowUp = "Maia-arrowUp"
    case arrowDown = "Maia-arrowDown"
    case arrowUpRight = "Maia-arrowUpRight"
    case transfer = "Maia-transfer"
    case refresh = "Maia-refresh"
    case undo = "Maia-undo"
    case download = "Maia-download"
    case upload = "Maia-upload"
    case branch = "Maia-branch"
    case git = "Maia-git"
    case battery = "Maia-battery"
    case batteryEmpty = "Maia-batteryEmpty"
    case bolt = "Maia-bolt"
    case calendar = "Maia-calendar"
    case chart = "Maia-chart"
    case chartLine = "Maia-chartLine"
    case chartPie = "Maia-chartPie"
    case clock = "Maia-clock"
    case history = "Maia-history"
    case cloudSun = "Maia-cloudSun"
    case cloud = "Maia-cloud"
    case cloudMoon = "Maia-cloudMoon"
    case rain = "Maia-rain"
    case drizzle = "Maia-drizzle"
    case snow = "Maia-snow"
    case sleet = "Maia-sleet"
    case storm = "Maia-storm"
    case fog = "Maia-fog"
    case sun = "Maia-sun"
    case moon = "Maia-moon"
    case cpu = "Maia-cpu"
    case crown = "Maia-crown"
    case copy = "Maia-copy"
    case dock = "Maia-dock"
    case drop = "Maia-drop"
    case more = "Maia-more"
    case alert = "Maia-alert"
    case drive = "Maia-drive"
    case gauge = "Maia-gauge"
    case settings = "Maia-settings"
    case globe = "Maia-globe"
    case hexagon = "Maia-hexagon"
    case hourglass = "Maia-hourglass"
    case humidity = "Maia-humidity"
    case info = "Maia-info"
    case key = "Maia-key"
    case link = "Maia-link"
    case location = "Maia-location"
    case lock = "Maia-lock"
    case search = "Maia-search"
    case memory = "Maia-memory"
    case minus = "Maia-minus"
    case music = "Maia-music"
    case network = "Maia-network"
    case number = "Maia-number"
    case image = "Maia-image"
    case plus = "Maia-plus"
    case power = "Maia-power"
    case logout = "Maia-logout"
    case sparkles = "Maia-sparkles"
    case share = "Maia-share"
    case star = "Maia-star"
    case temperature = "Maia-temperature"
    case trash = "Maia-trash"
    case video = "Maia-video"
    case activity = "Maia-activity"
    case wind = "Maia-wind"
    case close = "Maia-close"
    case closeCircle = "Maia-closeCircle"
    case play = "Maia-play"
    case pause = "Maia-pause"
    case volume = "Maia-volume"
    case volumeOff = "Maia-volumeOff"
    case skipForward = "Maia-skipForward"
    case skipBack = "Maia-skipBack"
    case headphones = "Maia-headphones"
    case earbuds = "Maia-earbuds"
    case keyboard = "Maia-keyboard"
    case mouse = "Maia-mouse"
    case laptop = "Maia-laptop"
    case trackpad = "Maia-trackpad"
    case terminal = "Maia-terminal"
    case code = "Maia-code"
    case grid = "Maia-grid"
    case eyeOff = "Maia-eyeOff"
    case shield = "Maia-shield"
    case help = "Maia-help"
    case tools = "Maia-tools"
    case circle = "Maia-circle"
    case appearance = "Maia-appearance"
    case app = "Maia-app"
    case target = "Maia-target"
    case rewind = "Maia-rewind"
    case forward = "Maia-forward"
    case pin = "Maia-pin"
    case edit = "Maia-edit"
    case flag = "Maia-flag"
    case userDisconnected = "Maia-userDisconnected"
    case calendarRemoved = "Maia-calendarRemoved"

    /// Model identifiers remain stable for persisted/native-menu compatibility.
    /// New shared components use DSIconName directly.
    static func fromLegacySymbol(_ symbol: String) -> Self? {
        switch symbol {
        case "checkmark": return .check
        case "checkmark.circle", "checkmark.circle.fill": return .checkCircle
        case "accessibility": return .accessibility
        case "chevron.down": return .chevronDown
        case "chevron.up": return .chevronUp
        case "chevron.left": return .chevronLeft
        case "chevron.right": return .chevronRight
        case "chevron.up.chevron.down": return .chevronsVertical
        case "arrow.up": return .arrowUp
        case "arrow.down": return .arrowDown
        case "arrow.up.right": return .arrowUpRight
        case "arrow.up.arrow.down": return .transfer
        case "arrow.clockwise", "arrow.triangle.2.circlepath", "arrow.trianglehead.2.clockwise.rotate.90": return .refresh
        case "arrow.counterclockwise": return .undo
        case "arrow.down.circle", "arrow.down.circle.fill": return .download
        case "arrow.up.circle": return .upload
        case "arrow.triangle.branch": return .branch
        case "point.3.connected.trianglepath.dotted": return .git
        case "battery.100percent", "battery.75percent", "battery.50percent", "battery.25percent": return .battery
        case "battery.0percent": return .batteryEmpty
        case "bolt", "bolt.fill", "bolt.horizontal.circle": return .bolt
        case "calendar", "calendar.badge.clock": return .calendar
        case "chart.bar", "chart.bar.xaxis": return .chart
        case "chart.xyaxis.line": return .chartLine
        case "chart.pie": return .chartPie
        case "clock", "clock.fill", "clock.badge.exclamationmark", "clock.badge.questionmark": return .clock
        case "clock.arrow.circlepath": return .history
        case "cloud.sun", "cloud.sun.fill": return .cloudSun
        case "cloud", "cloud.fill": return .cloud
        case "cloud.moon.fill": return .cloudMoon
        case "cloud.rain.fill": return .rain
        case "cloud.drizzle.fill": return .drizzle
        case "cloud.snow.fill": return .snow
        case "cloud.sleet.fill": return .sleet
        case "cloud.bolt.rain.fill": return .storm
        case "cloud.fog.fill": return .fog
        case "sun.max", "sun.max.fill", "sun.horizon.fill": return .sun
        case "moon", "moon.fill", "moon.stars.fill": return .moon
        case "cpu": return .cpu
        case "crown.fill": return .crown
        case "doc.on.doc": return .copy
        case "dock.rectangle": return .dock
        case "drop", "drop.fill": return .drop
        case "ellipsis", "ellipsis.circle", "ellipsis.circle.fill": return .more
        case "exclamationmark.triangle", "exclamationmark.triangle.fill", "exclamationmark.circle", "exclamationmark.circle.fill", "xmark.octagon.fill", "calendar.badge.exclamationmark": return .alert
        case "internaldrive", "internaldrive.fill", "externaldrive", "externaldrive.fill": return .drive
        case "gauge.with.dots.needle.0percent", "gauge.with.dots.needle.50percent", "gauge.with.dots.needle.100percent", "gauge.with.dots.needle.33percent": return .gauge
        case "gearshape", "gearshape.fill": return .settings
        case "globe": return .globe
        case "hexagon": return .hexagon
        case "hourglass": return .hourglass
        case "humidity": return .humidity
        case "info.circle", "info.circle.fill": return .info
        case "key.horizontal", "key.horizontal.fill": return .key
        case "link", "link.badge.plus": return .link
        case "location", "location.fill", "mappin.and.ellipse": return .location
        case "lock", "lock.fill": return .lock
        case "magnifyingglass": return .search
        case "memorychip": return .memory
        case "minus.circle": return .minus
        case "music.note": return .music
        case "network": return .network
        case "number", "textformat.123": return .number
        case "photo": return .image
        case "plus", "plus.circle", "plus.circle.fill": return .plus
        case "power": return .power
        case "rectangle.portrait.and.arrow.right": return .logout
        case "sparkle", "sparkles": return .sparkles
        case "square.and.arrow.up": return .share
        case "star", "star.fill": return .star
        case "thermometer.medium": return .temperature
        case "trash": return .trash
        case "video": return .video
        case "waveform.path.ecg": return .activity
        case "wind": return .wind
        case "xmark": return .close
        case "xmark.circle", "xmark.circle.fill": return .closeCircle
        case "play", "play.fill", "play.circle.fill": return .play
        case "pause", "pause.fill", "pause.circle.fill": return .pause
        case "speaker.wave.2.fill", "speaker.wave.3.fill": return .volume
        case "speaker.slash.fill": return .volumeOff
        case "forward.end.fill": return .skipForward
        case "backward.end.fill": return .skipBack
        case "headphones": return .headphones
        case "airpodspro", "airpodspro.chargingcase.wireless.fill": return .earbuds
        case "keyboard": return .keyboard
        case "computermouse.fill": return .mouse
        case "laptopcomputer": return .laptop
        case "magictrackpad": return .trackpad
        case "terminal": return .terminal
        case "chevron.left.forwardslash.chevron.right": return .code
        case "rectangle.split.2x2": return .grid
        case "eye.slash": return .eyeOff
        case "checkmark.shield.fill": return .shield
        case "questionmark.circle", "questionmark": return .help
        case "wrench.and.screwdriver.fill": return .tools
        case "circle", "circle.fill", "circle.dashed": return .circle
        case "circle.lefthalf.filled": return .appearance
        case "app.fill", "g.circle": return .app
        case "scope": return .target
        case "gobackward", "gobackward.10", "gobackward.15", "gobackward.30", "gobackward.5", "gobackward.60": return .rewind
        case "goforward", "goforward.10", "goforward.15", "goforward.30", "goforward.5", "goforward.60": return .forward
        case "pin", "pin.fill": return .pin
        case "pencil": return .edit
        case "flag.fill": return .flag
        case "person.crop.circle.badge.xmark": return .userDisconnected
        case "calendar.badge.minus": return .calendarRemoved
        default: return nil
        }
    }
}
