#!/usr/bin/env python3
"""Import only reviewed HugeIcons paths from a checksum-pinned npm archive.

Usage: python3 script/import_maia_icons.py /path/core-free-icons-4.3.3.tgz
No JavaScript is evaluated. Normal Xcode builds use the checked-in assets.
"""
import hashlib
import html
import json
from pathlib import Path
import re
import sys
import tarfile

root = Path(__file__).resolve().parent.parent
manifest = json.loads((root / "docs/research/maia-native/icons.json").read_text())
archive = Path(sys.argv[1])
assert hashlib.sha1(archive.read_bytes()).hexdigest() == manifest["sha1"], "Unexpected icon archive"
assets = root / "DockMagic/DockMagic/Assets.xcassets"
cases, aliases = [], []
with tarfile.open(archive) as package:
    for name, item in manifest["icons"].items():
        source = package.extractfile("package/dist/esm/" + item["source"] + ".js").read().decode()
        data = source[source.index("= [") + 2:source.index(";\n")]
        data = re.sub(r"(?<=[{,])\s*([a-zA-Z][a-zA-Z0-9]*):", r' "\1":', data)
        elements = json.loads(data)
        children = []
        for tag, attributes in elements:
            assert tag in {"path", "circle", "rect", "ellipse", "line", "polyline", "polygon"}
            pairs = []
            for key, value in attributes.items():
                if key == "key":
                    continue
                key = re.sub(r"[A-Z]", lambda m: "-" + m[0].lower(), key)
                value = "black" if value == "currentColor" else str(value)
                pairs.append(f'{key}="{html.escape(value, quote=True)}"')
            children.append(f'<{tag} {" ".join(pairs)}/>')
        svg = '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">' + "".join(children) + '</svg>\n'
        directory = assets / f"Maia-{name}.imageset"
        directory.mkdir(exist_ok=True)
        (directory / "icon.svg").write_text(svg)
        (directory / "Contents.json").write_text(json.dumps({
            "images": [{"filename": "icon.svg", "idiom": "universal"}],
            "info": {"author": "xcode", "version": 1},
            "properties": {"preserves-vector-representation": True, "template-rendering-intent": "template"}
        }, indent=2) + "\n")
        cases.append(f'    case {name} = "Maia-{name}"')
        if item["legacySymbols"]:
            symbols = ", ".join(json.dumps(s) for s in item["legacySymbols"])
            aliases.append(f"        case {symbols}: return .{name}")
    license_path = root / "DockMagic/DockMagic/Resources/MaiaFonts/HugeIcons-LICENSE.md"
    license_path.write_bytes(package.extractfile("package/LICENSE.md").read())

swift = '''// Generated by script/import_maia_icons.py; edit the reviewed manifest instead.
import Foundation

enum DSIconName: String, CaseIterable {
''' + "\n".join(cases) + '''

    /// Model identifiers remain stable for persisted/native-menu compatibility.
    /// New shared components use DSIconName directly.
    static func fromLegacySymbol(_ symbol: String) -> Self? {
        switch symbol {
''' + "\n".join(aliases) + '''
        default: return nil
        }
    }
}
'''
(root / "DockMagic/DockMagic/DesignSystem/Foundation/DSIconName.swift").write_text(swift)
print(f"Imported {len(cases)} reviewed icons from {manifest['package']}@{manifest['version']}")
